content = open('pink_edge.py').read()
content = content.replace('--bg: #0a0e1a;', '--bg: #ffffff;')
content = content.replace('--surface: #111827;', '--surface: #ffffff;')
content = content.replace('--surface-alt: #1e293b;', '--surface-alt: #f5f5f5;')
content = content.replace('--surface-hover: #334155;', '--surface-hover: #e8eaf6;')
content = content.replace('--border: #1e293b;', '--border: #e0e0e0;')
content = content.replace('--border-light: #334155;', '--border-light: #bdbdbd;')
content = content.replace('--text: #f1f5f9;', '--text: #212121;')
content = content.replace('--text-muted: #94a3b8;', '--text-muted: #5f6368;')
content = content.replace('--text-light: #64748b;', '--text-light: #9e9e9e;')
content = content.replace('--primary: #14b8a6;', '--primary: #1a237e;')
content = content.replace('--primary-light: #2dd4bf;', '--primary-light: #3949ab;')
content = content.replace('--primary-dark: #0d9488;', '--primary-dark: #0d1557;')
content = content.replace('--primary-bg: rgba(20, 184, 166, 0.1);', '--primary-bg: rgba(26, 35, 126, 0.08);')
content = content.replace('--accent: #ec4899;', '--accent: #e91e63;')
content = content.replace('--accent-light: #f472b6;', '--accent-light: #f06292;')
content = content.replace('--accent-dark: #db2777;', '--accent-dark: #c2185b;')
content = content.replace('--success: #10b981;', '--success: #2e7d32;')
content = content.replace('--danger: #ef4444;', '--danger: #c62828;')
content = content.replace('--warning: #f59e0b;', '--warning: #f9a825;')
content = content.replace('section[data-testid="stSidebar"] { background: var(--surface) !important; border-right: 1px solid var(--border) !important; }', 'section[data-testid="stSidebar"] { background: #ffffff !important; border-right: 1px solid #e0e0e0 !important; }')
content = content.replace('.stApp { background: var(--bg);', '.stApp { background: #ffffff;')
open('pink_edge.py', 'w').write(content)
print('Done')
